#!/usr/bin/env python3
"""Generate theme/head.hbs: per-page descriptions and link-preview tags.

Two problems this fixes, both invisible on the site itself:

  Every page shipped the SAME <meta description>, the one from
  book.toml. Search engines commonly discard duplicate descriptions
  across a domain and write their own from the page text. Nineteen
  pages, one description, is nineteen pages competing with the same
  snippet.

  There were no Open Graph or Twitter tags at all, so the URL unfurled
  nowhere: posting it in Slack or anywhere else produced a bare link
  with no title, no summary and no picture, for a book that has twelve
  commissioned drawings.

mdBook has no per-page front matter, so the description has to come from
a lookup on `path`, which is what the generated `#if` chain below is.
One `{{#if}}` per page rather than a chained `{{else if}}`, because the
plain form is supported by every handlebars implementation and this file
is not worth being clever in.

Descriptions come from the chapter epigraph plus the opening sentence,
which is the closest thing the book already has to a précis, so they
stay in the author's voice rather than being invented here.

    python3 pipeline/make_head.py
"""
import html
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT = ROOT / "theme" / "head.hbs"
BASE = "https://derivingsystems.com"
CARD = f"{BASE}/img/social-card.png"
MAXLEN = 155

# Pages that open with a single short sentence, or none, and so cannot
# produce a useful snippet from their own prose.
OVERRIDE = {
    "index.md": "Performance engineering derived from a dozen constants and "
                "long division. Twelve chapters, each opening with a "
                "measurement that does not fit.",
    "preface.md": "Why this book exists, the rule that nothing is looked up, "
                  "and how to revise from it by retrieval rather than by "
                  "rereading it.",
    "introduction.md": "The method itself: name the candidates, name the "
                       "ratio between them, do the division, and see which "
                       "ones survive it.",
    "rules.md": "All fourteen rules of Deriving Systems on one page, each "
                "linking back to the derivation that earned it. The page to "
                "open at eleven at night.",
    "challenges.md": "Every question in Deriving Systems, stripped of context "
                     "and answers. Forty-eight challenges, for revision by "
                     "retrieval rather than rereading.",
}


def clamp(s):
    """Search snippets are cut near 160 characters. Land under that on a
    word boundary rather than being truncated mid-word by somebody else."""
    s = " ".join(s.split())
    if len(s) <= MAXLEN:
        return s
    return s[:MAXLEN - 3].rsplit(" ", 1)[0].rstrip(".,;:") + "..."


def describe(path, text):
    if path in OVERRIDE:
        return clamp(OVERRIDE[path])

    epigraph = ""
    m = re.search(r"^> (.+)$", text, re.M)
    if m:
        epigraph = m.group(1).strip()

    body = re.sub(r"^#.*$", "", text, flags=re.M)
    body = re.sub(r"<[^>]+>", "", body)
    body = re.sub(r"^>.*$", "", body, flags=re.M)
    body = re.sub(r"```.*?```", "", body, flags=re.S)
    first = ""
    for para in (p.strip() for p in body.split("\n\n")):
        if para and not para.startswith(("|", "-", "*", "1.")):
            first = " ".join(para.split())
            break

    return clamp(f"{epigraph} {first}".strip() if epigraph else first)


def title_for(path, text):
    m = re.search(r"^# (.+)$", text, re.M)
    name = m.group(1).strip() if m else path
    return ("Deriving Systems" if path == "index.md"
            else f"{name} · Deriving Systems")


def main():
    summary = (SRC / "SUMMARY.md").read_text()
    pages = ["index.md"] + [
        m.group(1) for m in re.finditer(r"\]\(\./([\w-]+\.md)\)", summary)
        if m.group(1) != "index.md"
    ]
    seen, ordered = set(), []
    for p in pages:
        if p not in seen and (SRC / p).exists():
            seen.add(p)
            ordered.append(p)

    lines = [
        "{{!-- GENERATED by pipeline/make_head.py. Do not edit by hand. --}}",
        "{{!-- Regenerate after adding a page, then commit the result. --}}",
        "",
        '<meta property="og:site_name" content="Deriving Systems">',
        '<meta property="og:type" content="article">',
        '<meta property="og:locale" content="en_GB">',
        f'<meta property="og:image" content="{CARD}">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        '<meta property="og:image:alt" content="Deriving Systems: performance '
        'engineering from first principles. A postman posts a letter into a '
        'pillar box while the mail spills out of a crack in its side.">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:image" content="{CARD}">',
        '<meta name="author" content="Venugopalan Iyengar">',
        "",
    ]

    for p in ordered:
        text = (SRC / p).read_text()
        desc = html.escape(describe(p, text), quote=True)
        title = html.escape(title_for(p, text), quote=True)
        url = BASE + "/" + ("" if p == "index.md" else p[:-3] + ".html")
        lines += [
            '{{#if (eq path "%s")}}' % p,
            f'<link rel="canonical" href="{url}">',
            f'<meta name="description" content="{desc}">',
            f'<meta property="og:url" content="{url}">',
            f'<meta property="og:title" content="{title}">',
            f'<meta property="og:description" content="{desc}">',
            f'<meta name="twitter:title" content="{title}">',
            f'<meta name="twitter:description" content="{desc}">',
            "{{/if}}",
        ]

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} for {len(ordered)} pages")
    for p in ordered:
        d = describe(p, (SRC / p).read_text())
        print(f"  {p:34s} {len(d):3d}  {d[:62]}")


if __name__ == "__main__":
    main()
